spring:
  application:
    name: skyBootFramework
  datasource:
    ## 主库
    master:
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: yang
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifeTime: 1800000
      maximumPoolSize: 100
      minimumIdle: 10
      poolName: masterDataSource
    ## 从库
    slave:
      ## 是否开启从库
      enabled: false
      url: jdbc:mysql://localhost:3306/db_class?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: yang
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifeTime: 1800000
      maximumPoolSize: 100
      minimumIdle: 10
      poolName: slaveDataSource
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器端口号
      port: 6379
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: 123456
      lettuce:
        pool:
          # 最大阻塞等待时间，负数表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 5
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
          max-active: 20
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8080
logging:
  config: classpath:log4j2.xml

login:
  ## token-header
  header: TOKEN
  ## redis放重复前缀
  PREVENT_DUPLICATION_PREFIX: PREVENT_DUPLICATION_PREFIX

## jwt配置
jwt:
  config:
    ## 加密密钥
    secret: asiuf62asd6daw125asd
    ## 过期时间
    expire: 3600
